library;

import 'package:clean_arch_base/src/core/shared/extensions/widgets/padding_extension.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:injectable/injectable.dart';

import '../../../../../flavors.dart';
import '../../../../config/language/locale_keys.g.dart';
import '../../../../config/res/assets.gen.dart';
import '../../../../config/res/config_imports.dart';
import '../../../../core/navigation/navigator.dart';
import '../../../../core/shared/cubits/user_cubit/user_cubit.dart';
import '../../../../core/shared/extensions/text_style_extensions.dart';
import '../../../../core/shared/extensions/widgets/widget_extentions.dart';
import '../../../../core/state/async/async.dart';
import '../../../../core/widgets/handling_views/empty_widget.dart';
import '../../../../core/widgets/icon_widget.dart';
import '../../../../core/widgets/navigation_bar/app_bottom_navigation_bar.dart';
import '../../../../core/widgets/navigation_bar/custom_navigation_bar.dart';
import '../../../../core/widgets/navigation_bar/navigation_bar_entity.dart';
import '../../../../core/widgets/scaffolds/arrow_widget.dart';
import '../../domain/entities/home_entity.dart';
import '../../domain/entities/recent_request_entity.dart';
import '../../domain/usecases/get_home_usecase.dart';
import '../../../new_request/presentation/imports/new_request_imports.dart';
import '../../../my_team/presentation/imports/my_team_imports.dart';
import '../../../notifications/presentation/imports/notifications_imports.dart';
import '../../../orders/presentation/imports/orders_imports.dart';
import '../../../profile/presentation/imports/profile_imports.dart';
import '../../../provider/employees/presentation/imports/employees_imports.dart';
import '../../../provider/requests/presentation/imports/requests_imports.dart';

part '../view/home_screen.dart';
part '../view/main_tap_csreen.dart';
part '../cubits/home_cubit.dart';
part '../controllers/home_view_controller.dart';
part '../widgets/home_body.dart';
part '../widgets/requests_section.dart';
part '../widgets/request_card.dart';
part '../widgets/custom_appBar.dart';
part '../widgets/home_header.dart';
part '../widgets/balance_card.dart';
part '../widgets/home_tabs.dart';
part '../widgets/custom_logo_app.dart';
part '../widgets/home_placeholder_tab.dart';
