// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:clean_arch_base/src/core/network/offline/queued_operation.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(QueuedOperationAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(QueuedOperationAdapter());
  }
}
