library;

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';

import '../../../../../flavors.dart';
import '../../../../config/language/languages.dart';
import '../../../../config/language/locale_keys.g.dart';
import '../../../../config/res/assets.gen.dart';
import '../../../../config/res/config_imports.dart';
import '../../../../core/navigation/navigator.dart';
import '../../../../core/network/auth/token_storage.dart';
import '../../../../core/network/error/failures.dart';
import '../../../../core/shared/extensions/base_state.dart';
import '../../../../core/shared/extensions/text_style_extensions.dart';
import '../../../../core/shared/extensions/widgets/padding_extension.dart';
import '../../../../core/shared/extensions/widgets/widget_extentions.dart';
import '../../../../core/state/async/async.dart';
import '../../../../core/widgets/custom_messages.dart';
import '../../../../core/widgets/icon_widget.dart';
import '../../../../core/widgets/image_widgets/cached_image.dart';
import '../../../logout/presentation/imports/logout_imports.dart';
import '../../../login/domain/entities/employee_entity.dart';
import '../../../login/domain/entities/login_entity.dart';
import '../../../login/presentation/imports/login_imports.dart';
import '../../../remote_work/presentation/imports/remote_work_imports.dart';
import '../../domain/usecases/get_profile_use_case.dart';

part '../controllers/profile_view_controller.dart';
part '../cubits/profile_cubit.dart';
part '../view/profile_screen.dart';
part '../widgets/profile_balance_card.dart';
part '../widgets/profile_body.dart';
part '../widgets/profile_content.dart';
part '../widgets/profile_header.dart';
part '../widgets/profile_image_card.dart';
part '../widgets/profile_info_item.dart';
part '../widgets/profile_menu_item.dart';
