import 'package:injectable/injectable.dart';

import '../../../config/res/config_imports.dart';
import '../../network/cancel/request_cancellation_manager.dart';
import '../../network/cubits/connectivity_cubit.dart';
import '../../network/cubits/offline_queue_cubit.dart';
import '../../network/auth/token_storage.dart';
import '../../network/dio_client.dart';
import '../../network/offline/offline_queue_manager.dart';
import '../../notifications/notification_manager.dart';
import 'setup_service_locators.config.dart';

/// Entry point called once from `main()` before `runApp`.
///
/// Two layers of registration:
///   1. [setUpGeneralDependencies] — manual registrations for services that
///      can't be reached by `@injectable` (private constructors, factory
///      singletons, things owned by a package we don't control, …).
///   2. `injector.init()` — generated by `injectable_generator`. Picks up
///      every `@injectable` / `@lazySingleton` / `@singleton` annotation in
///      `lib/` and wires them automatically.
///
/// Put cubits and use-cases on the annotation track. Keep this file for
/// pure infrastructure (dio, storage, notification stack, queues, etc.).
@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
void setUpServiceLocator() {
  setUpGeneralDependencies();
  injector.init();
}

void setUpGeneralDependencies() {
  // Infrastructure singletons that have private constructors / factory
  // patterns — `@injectable` can't reach them, so we wire by hand.
  //
  // `TokenStorage` exposes a single static `instance` (hydrated from disk
  // in `main()`). Register it here so DI lookups resolve to the SAME object
  // — otherwise the AuthInterceptor would read an un-hydrated second copy.
  injector.registerLazySingleton<TokenStorage>(() => TokenStorage.instance);
  injector.registerLazySingleton<DioClient>(() => DioClient());
  injector.registerLazySingleton<RequestCancellationManager>(
    () => RequestCancellationManager(),
  );
  injector.registerLazySingleton<OfflineQueueManager>(
    () => OfflineQueueManager(),
  );
  injector.registerLazySingleton<NotificationManager>(
    () => NotificationManager.instance,
  );

  // Cross-cutting cubits not driven by features.
  injector.registerLazySingleton<ConnectivityCubit>(() => ConnectivityCubit());
  injector.registerLazySingleton<OfflineQueueCubit>(() => OfflineQueueCubit());
}
